%% Mermaid Diagram for the tagcore rust library

classDiagram
direction TB
    note for Workspace "Must exist for tags to be used"
    class Workspace {
        + directory_root : PathBuf
        + name : String
	    + all_tagfiles : HashMap of PathBuf to TagFile
	    + tag_cache : HashSet of Strings
	    
        + open_or_create_workspace(path: PathBuf, name: String) Result
        + add_tag_to_file(file_name: PathBuf, tag: String) Result
	    + remove_tag_from_file(file_name: PathBuf, tag: String) Result
        + scan_workspace_for_tags() Result
        + get_all_tags_strings() List of Strings
	    + query(QueryType)
        + get_tags_for_file_name(path_to_file: PathBuf) Vec of Tag
    }

    note for TagFile "Cannot exist on its own."
    note for TagFile "In-Memory Model for Tags for a workspace. Corresponds to .tag_workspace file in each subdir."
    class TagFile {
	    - full_path_to_tagfile : PathBuf

        + from_file_in_dir(path: Path) TagFile

	    + add_tag_to_file_in_self() Result
	    + remove_tag_from_file_in_self() Result

        + get_all_tags_for_filename(file_name: String) Vec of Tag

        - save_to_disk() Result
    }

    note for Tag "Enum"
    class Tag {

    }
    class Simple {value: String}
    class KV {
        key: String
        value: String
    }

    Simple --|> Tag
    KV --|> Tag

    note for WorkspaceWatcher "Only exists if an application sets one up for a workspace. Handles external rename / move."
    class WorkspaceWatcher {
    }

    TagFile --* Workspace
    Tag --* TagFile
