from typing import List, Dict

class TagWorkspace:
    @staticmethod
    def open_or_create_workspace(directory: str, name: str) -> TagWorkspace: ...
    def add_tag_to_file(self, path_to_file: str, tag_1: str, tag_2: str) -> None: ...
    def remove_tag_from_file(self, path_to_file: str, tag_1: str, tag_2: str) -> None: ...
    def scan_for_tagfiles(self) -> None: ...