from typing import List, Dict, Optional

class Tag:
    @staticmethod
    def simple(value: str) -> Tag: ...
    @staticmethod
    def kv(key: str, value: str) -> Tag: ...
    @property
    def kind(self) -> str: ...
    def __repr__(self) -> str: ...

    def is_simple(self) -> bool: ...
    def is_kv(self) -> bool: ...
    @property
    def simple_value(self) -> Optional[str]: ...
    @property
    def kv_key(self) -> Optional[str]: ...
    @property
    def kv_value(self) -> Optional[str]: ...

class TagWorkspace:
    @staticmethod
    def open_or_create_workspace(directory: str, name: str) -> TagWorkspace: ...
    def scan_for_tagfiles(self) -> None: ...
    def add_tag_to_file(self, path_to_file: str, tag_1: str, tag_2: str) -> None: ...
    def remove_tag_from_file(self, path_to_file: str, tag_1: str, tag_2: str) -> None: ...
    def get_tags_for_file_name(self, path_to_file: str) -> list[Tag]: ...
    def get_name(self) -> str: ...
    def query_exact(self, text: str, simple: bool, key: bool, value: bool) -> Dict[str, list[Tag]]: ...
    def query_fuzzy(self, text: str, simple: bool, key: bool, value: bool) -> Dict[str, list[Tag]]: ...