from typing import List, Dict

class Tag:
    @staticmethod
    def simple(value: str) -> Tag: ...
    @staticmethod
    def kv(key: str, value: str) -> Tag: ...
    @property
    def kind(self) -> str: ...
    def __repr__(self) -> str: ...

class TagWorkspace:
    @staticmethod
    def open_or_create_workspace(directory: str, name: str) -> TagWorkspace: ...
    def add_tag_to_file(self, path_to_file: str, tag_1: str, tag_2: str) -> None: ...
    def remove_tag_from_file(self, path_to_file: str, tag_1: str, tag_2: str) -> None: ...
    def scan_for_tagfiles(self) -> None: ...
    def get_tags_for_file_name(self, path_to_file: str) -> list[Tag]: ...